### ISSUE TITLE
Reaching out

### ISSUE THREAD

**Issue by antoninadert** [BenTheElder/site#5]
Hello, I stumbled upon your blog post https://elder.dev/posts/open-source-virtual-background/
And I didn't find a mail or some better way to reach out so I created this issue (feel free to delete)

I am just a random guy who like open source so when I saw your post I had this idea : 

Do you know Jitsi ? They build a thing like Zoom but open source ! As you have done the virtual background and I saw Jitsi still need this feature : https://community.jitsi.org/t/virtual-backgrounds-using-green-screen/31173

I would just like to drop the idea here so you can maybe show your work to them, get in touch and hopefully integrate virtual background in Jitsi, which would be an amazing thing for the community.

Anyway this is your call now, I just wanted to make sure that you know about this opportunity.

Have a nice day :)

And amazing job btw

**Comment by BenTheElder** [comment]
Hi, for someone familiar with the codebase it shouldn't be very problematic to replace blur with background replacement since they're already identifying the foreground & background using bodypix to do the blur effect. I imagine most of the remaining work is in wiring up the UI to allow the user to supply an image...

I'm not really a web developer and I don't use yet use jitsi myself though :-)

This post is a fun hack, but I wouldn't recommend that they bother looking at it for this purpose, they should probably just extend their existing use of bodypix :-)

**Comment by BenTheElder** [comment]
BTW my contact info including email is listed pretty prominently on my homepage https://elder.dev/ :-)

Thanks for the suggestion!
