### ISSUE TITLE
Capture only requests exceptions on virtual background

### ISSUE THREAD

**Issue by ocelotsloth** [BenTheElder/site#8]
Hey thanks for your great post. I had a suggestion based on an issue I ran across.

Here: https://github.com/BenTheElder/site/blame/master/content/posts/open-source-virtual-background.md#L479

You have a section as follows:
```python
    while mask is None:
        try:
            mask = get_mask(frame)
        except:
            print("mask request failed, retrying")
```

The way it's written causes issues when the system tries to kill the process through either another process sending a kill signal or a user sending CTRL+C.

Catching only `requests.RequestExceptions` should take care of what you're after while not also swallowing kill signals.

```python
    while mask is None:
        try:
            mask = get_mask(frame)
        except requests.RequestException:
            print("mask request failed, retrying")
```

If you've been using this script yourself you should notice that it is a whole lot easier to kill the script.

**Comment by BenTheElder** [comment]
This is a good suggestion, thanks.

The script in the article is a quick hack and is generally terser and suboptimal vs "production". For now I've been leaving it intentionally simpler than what I'm running to focus on outlining the approach, but I don't see any reason not to make this correction.

> If you've been using this script yourself you should notice that it is a whole lot easier to kill the script.

I haven't had any trouble actually, but that's because I run it in a container as outlined in the article. `docker rm -f fakecam` conveniently sends SIGKILL.

**Comment by BenTheElder** [comment]
I've made this change, and I'm considering a follow-up regarding generally improving the scripts.

thanks :-)
